services:
  postgres:
    image: postgres:15
    container_name: tracker-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracker_db
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tracker-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: